apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: ds-one
spec:
  template:
    metadata:
      labels:
        system: DaemonSetOne
    spec:
      containers:
      - name: nginx
#        image: nginx:1.9.1
        image: nginx:1.12.1-alpine
        ports:
        - containerPort: 80
